// Code generated by protoc-gen-go. DO NOT EDIT.
// source: software.proto

package software_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common_go_proto "github.com/grafeas/grafeas/proto/v1beta1/common_go_proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Software_Kind int32

const (
	// Unknown
	Software_KIND_UNSPECIFIED Software_Kind = 0
	// OpenShift or Kubernetes Operator
	Software_OPERATOR Software_Kind = 1
)

var Software_Kind_name = map[int32]string{
	0: "KIND_UNSPECIFIED",
	1: "OPERATOR",
}

var Software_Kind_value = map[string]int32{
	"KIND_UNSPECIFIED": 0,
	"OPERATOR":         1,
}

func (x Software_Kind) String() string {
	return proto.EnumName(Software_Kind_name, int32(x))
}

func (Software_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{0, 0}
}

// A note that indicates a type of software group. This note
// exists in a provider's project. A `Software` occurrence is created in a
// consumer's project and contains a list of resources that makeup the software group.
type Software struct {
	// The software bundle Kind
	Kind                 Software_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=grafeas.v1beta1.software.Software_Kind" json:"kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Software) Reset()         { *m = Software{} }
func (m *Software) String() string { return proto.CompactTextString(m) }
func (*Software) ProtoMessage()    {}
func (*Software) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{0}
}

func (m *Software) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Software.Unmarshal(m, b)
}
func (m *Software) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Software.Marshal(b, m, deterministic)
}
func (m *Software) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Software.Merge(m, src)
}
func (m *Software) XXX_Size() int {
	return xxx_messageInfo_Software.Size(m)
}
func (m *Software) XXX_DiscardUnknown() {
	xxx_messageInfo_Software.DiscardUnknown(m)
}

var xxx_messageInfo_Software proto.InternalMessageInfo

func (m *Software) GetKind() Software_Kind {
	if m != nil {
		return m.Kind
	}
	return Software_KIND_UNSPECIFIED
}

type Details struct {
	Resources            []*common_go_proto.Resource `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{1}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetResources() []*common_go_proto.Resource {
	if m != nil {
		return m.Resources
	}
	return nil
}

type GenericDetails struct {
	Details              map[string]string `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GenericDetails) Reset()         { *m = GenericDetails{} }
func (m *GenericDetails) String() string { return proto.CompactTextString(m) }
func (*GenericDetails) ProtoMessage()    {}
func (*GenericDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{2}
}

func (m *GenericDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericDetails.Unmarshal(m, b)
}
func (m *GenericDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericDetails.Marshal(b, m, deterministic)
}
func (m *GenericDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericDetails.Merge(m, src)
}
func (m *GenericDetails) XXX_Size() int {
	return xxx_messageInfo_GenericDetails.Size(m)
}
func (m *GenericDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericDetails.DiscardUnknown(m)
}

var xxx_messageInfo_GenericDetails proto.InternalMessageInfo

func (m *GenericDetails) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

type OperatorDetails struct {
	Operators            []*OperatorIdentifier `protobuf:"bytes,1,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OperatorDetails) Reset()         { *m = OperatorDetails{} }
func (m *OperatorDetails) String() string { return proto.CompactTextString(m) }
func (*OperatorDetails) ProtoMessage()    {}
func (*OperatorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{3}
}

func (m *OperatorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorDetails.Unmarshal(m, b)
}
func (m *OperatorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorDetails.Marshal(b, m, deterministic)
}
func (m *OperatorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorDetails.Merge(m, src)
}
func (m *OperatorDetails) XXX_Size() int {
	return xxx_messageInfo_OperatorDetails.Size(m)
}
func (m *OperatorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorDetails proto.InternalMessageInfo

func (m *OperatorDetails) GetOperators() []*OperatorIdentifier {
	if m != nil {
		return m.Operators
	}
	return nil
}

type OperatorIdentifier struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorIdentifier) Reset()         { *m = OperatorIdentifier{} }
func (m *OperatorIdentifier) String() string { return proto.CompactTextString(m) }
func (*OperatorIdentifier) ProtoMessage()    {}
func (*OperatorIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce2797c420615c95, []int{4}
}

func (m *OperatorIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorIdentifier.Unmarshal(m, b)
}
func (m *OperatorIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorIdentifier.Marshal(b, m, deterministic)
}
func (m *OperatorIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorIdentifier.Merge(m, src)
}
func (m *OperatorIdentifier) XXX_Size() int {
	return xxx_messageInfo_OperatorIdentifier.Size(m)
}
func (m *OperatorIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorIdentifier proto.InternalMessageInfo

func (m *OperatorIdentifier) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OperatorIdentifier) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("grafeas.v1beta1.software.Software_Kind", Software_Kind_name, Software_Kind_value)
	proto.RegisterType((*Software)(nil), "grafeas.v1beta1.software.Software")
	proto.RegisterType((*Details)(nil), "grafeas.v1beta1.software.Details")
	proto.RegisterType((*GenericDetails)(nil), "grafeas.v1beta1.software.GenericDetails")
	proto.RegisterMapType((map[string]string)(nil), "grafeas.v1beta1.software.GenericDetails.DetailsEntry")
	proto.RegisterType((*OperatorDetails)(nil), "grafeas.v1beta1.software.OperatorDetails")
	proto.RegisterType((*OperatorIdentifier)(nil), "grafeas.v1beta1.software.OperatorIdentifier")
}

func init() { proto.RegisterFile("software.proto", fileDescriptor_ce2797c420615c95) }

var fileDescriptor_ce2797c420615c95 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x51, 0xcf, 0xd2, 0x30,
	0x14, 0x75, 0x80, 0xf2, 0x71, 0x25, 0xb8, 0x34, 0x3c, 0x4c, 0x7c, 0x21, 0x7b, 0x91, 0x18, 0x53,
	0x02, 0xc6, 0x68, 0xf0, 0x09, 0x64, 0x92, 0x49, 0xc2, 0x48, 0xd1, 0x17, 0x13, 0x43, 0xca, 0x56,
	0xb0, 0x81, 0xb5, 0xa4, 0x2b, 0x18, 0x7e, 0x8c, 0x2f, 0xfe, 0x52, 0xc3, 0x68, 0xe5, 0x23, 0x64,
	0x4f, 0xf7, 0x9e, 0x7b, 0xcf, 0x39, 0x3d, 0x6d, 0x0a, 0x8d, 0x4c, 0xae, 0xf5, 0x6f, 0xaa, 0x18,
	0xde, 0x2b, 0xa9, 0x25, 0xf2, 0x36, 0x8a, 0xae, 0x19, 0xcd, 0xf0, 0xb1, 0xb7, 0x62, 0x9a, 0xf6,
	0xb0, 0xdd, 0xb7, 0x5a, 0x39, 0xa1, 0x6b, 0xe6, 0xdd, 0x58, 0xa6, 0xa9, 0x14, 0x17, 0x95, 0x9f,
	0xc1, 0xc3, 0xc2, 0xf0, 0xd0, 0x27, 0xa8, 0x6c, 0xb9, 0x48, 0x3c, 0xa7, 0xed, 0x74, 0x1a, 0xfd,
	0xd7, 0xb8, 0xc8, 0x10, 0x5b, 0x05, 0x9e, 0x72, 0x91, 0x90, 0x5c, 0xe4, 0xbf, 0x81, 0xca, 0x19,
	0xa1, 0x26, 0xb8, 0xd3, 0x70, 0x36, 0x5e, 0x7e, 0x9f, 0x2d, 0xe6, 0xc1, 0xe7, 0xf0, 0x4b, 0x18,
	0x8c, 0xdd, 0x27, 0xa8, 0x0e, 0x0f, 0xd1, 0x3c, 0x20, 0xc3, 0x6f, 0x11, 0x71, 0x1d, 0x7f, 0x04,
	0xd5, 0x31, 0xd3, 0x94, 0xef, 0x32, 0xf4, 0x01, 0x6a, 0x8a, 0x65, 0xf2, 0xa0, 0x62, 0x96, 0x79,
	0x4e, 0xbb, 0xdc, 0x79, 0xde, 0x7f, 0x79, 0x77, 0x30, 0x31, 0x0c, 0x72, 0xe5, 0xfa, 0x7f, 0x1c,
	0x68, 0x4c, 0x98, 0x60, 0x8a, 0xc7, 0xd6, 0x2b, 0x82, 0x6a, 0x72, 0x69, 0x8d, 0xd3, 0xfb, 0xe2,
	0x2b, 0xdc, 0x4a, 0xb1, 0xa9, 0x81, 0xd0, 0xea, 0x44, 0xac, 0x4b, 0x6b, 0x00, 0xf5, 0xc7, 0x0b,
	0xe4, 0x42, 0x79, 0xcb, 0x4e, 0xf9, 0xfb, 0xd4, 0xc8, 0xb9, 0x45, 0x4d, 0x78, 0x7a, 0xa4, 0xbb,
	0x03, 0xf3, 0x4a, 0xf9, 0xec, 0x02, 0x06, 0xa5, 0x8f, 0x8e, 0xff, 0x13, 0x5e, 0x44, 0x7b, 0xa6,
	0xa8, 0x96, 0xca, 0xe6, 0xfb, 0x0a, 0x35, 0x69, 0x46, 0x36, 0xe1, 0xdb, 0xe2, 0x84, 0x56, 0x1d,
	0x26, 0x4c, 0x68, 0xbe, 0xe6, 0x4c, 0x91, 0xab, 0xdc, 0x1f, 0x01, 0xba, 0x27, 0x20, 0x04, 0x15,
	0x41, 0x53, 0x66, 0x12, 0xe6, 0x3d, 0xf2, 0xa0, 0x7a, 0x64, 0x2a, 0xe3, 0x52, 0x98, 0x90, 0x16,
	0x8e, 0x28, 0xbc, 0xe2, 0xb2, 0x30, 0xc0, 0xdc, 0xf9, 0x31, 0xd8, 0x70, 0xfd, 0xeb, 0xb0, 0xc2,
	0xb1, 0x4c, 0xbb, 0x86, 0xf6, 0xbf, 0xde, 0xfe, 0x29, 0x2b, 0x5a, 0x6e, 0xe4, 0x32, 0xdf, 0xfc,
	0x2d, 0x95, 0x27, 0x64, 0xb8, 0x7a, 0x96, 0x83, 0x77, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0xa9, 0xcc, 0xb1, 0xad, 0x02, 0x00, 0x00,
}
